=== ssyangy/q/q-util/src/main/resources/q-serialize.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://serialize.q.com.cn" xmlns="http://serialize.q.com.cn"
	elementFormDefault="qualified">
	<xs:element name="method">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="methodCall" type="methodCallType" />
				<xs:element name="methodResponse" type="methodRespType" />
			</xs:sequence>
			<xs:attribute name="interfaceName" type="xs:string" use="required" />
			<xs:attribute name="interfaceVersion" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="methodCallType">
		<xs:sequence>
			<xs:element name="params" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="param" type="callParamType"
							minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="apiName" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="methodRespType">
		<xs:sequence>
			<xs:element name="param" type="respParamType" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:group name="callParamElementGroup">
		<xs:choice>
			<xs:element name="type" type="callTypeType" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="switch" type="callSwitchType" minOccurs="0"
				maxOccurs="1" />
		</xs:choice>
	</xs:group>

	<xs:group name="respParamElementGroup">
		<xs:sequence>
			<xs:element name="type" type="respTypeType" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:group>

	<xs:attributeGroup name="callParamAttributeGroup">
		<xs:attribute name="type" type="memberTypeAttrType" use="optional" />
		<xs:attribute name="apiName" type="apiNameAttrType" use="optional" />
		<xs:attribute name="apiType" type="memberTypeAttrType"
			use="optional" />
	</xs:attributeGroup>

	<xs:attributeGroup name="respParamAttributeGroup">
		<xs:attribute name="type" type="memberTypeAttrType" use="optional" />
		<xs:attribute name="apiName" type="xs:string" use="optional" />
		<xs:attribute name="apiType" type="memberTypeAttrType"
			use="optional" />
	</xs:attributeGroup>

	<xs:attributeGroup name="callMemberAttributeGroup">
		<xs:attribute name="apiName" type="apiNameAttrType" use="optional" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="type" type="memberTypeAttrType" use="optional" />
	</xs:attributeGroup>

	<xs:attributeGroup name="respMemberAttributeGroup">
		<xs:attribute name="apiName" type="xs:string" use="optional" />
		<xs:attribute name="name" type="xs:string" use="optional" />
		<xs:attribute name="apiType" type="memberTypeAttrType"
			use="optional" />
		<xs:attribute name="apiArrayItemName" type="xs:string"
			use="optional" />
	</xs:attributeGroup>

	<xs:complexType name="callParamType">
		<xs:group ref="callParamElementGroup" />
		<xs:attributeGroup ref="callParamAttributeGroup" />
	</xs:complexType>

	<xs:complexType name="respParamType">
		<xs:group ref="respParamElementGroup" />
		<xs:attributeGroup ref="respParamAttributeGroup" />
		<xs:attribute name="exceptionExpress" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="(\w+)?=(true|false)(,(\w+)?){2}" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>

	</xs:complexType>

	<xs:complexType name="callMemberType">
		<xs:choice>
			<xs:element name="type" type="callTypeType" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="switch" type="callSwitchType" minOccurs="0"
				maxOccurs="1" />
		</xs:choice>
		<xs:attributeGroup ref="callMemberAttributeGroup" />
	</xs:complexType>

	<xs:complexType name="respMemberType">
		<xs:choice>
			<xs:element name="type" type="respTypeType" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="switch" type="respSwitchType" minOccurs="0"
				maxOccurs="1" />
		</xs:choice>
		<xs:attributeGroup ref="respMemberAttributeGroup" />
	</xs:complexType>

	<xs:complexType name="callSwitchType">
		<xs:sequence>
			<xs:element name="case" type="callSwitchCaseType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="default" type="callSwitchDefaultType"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="respSwitchType">
		<xs:sequence>
			<xs:element name="case" type="respSwitchCaseType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="default" type="respSwitchDefaultType"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="respSwitchCaseType">
		<xs:attribute name="apiValue" type="xs:string" use="optional" />
		<xs:attribute name="value" type="xs:string" use="required" />
		<xs:attribute name="apiType" type="switchCaseTypeAttrType"
			use="optional" />
		<xs:attribute name="type" type="switchCaseTypeAttrType"
			use="required" />
	</xs:complexType>

	<xs:complexType name="callSwitchCaseType">
		<xs:attribute name="apiValue" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="optional" />
		<xs:attribute name="apiType" type="switchCaseTypeAttrType"
			use="required" />
		<xs:attribute name="type" type="switchCaseTypeAttrType"
			use="optional" />
	</xs:complexType>

	<xs:complexType name="respSwitchDefaultType">
		<xs:attribute name="apiValue" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="callSwitchDefaultType">
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="callTypeType">
		<xs:choice minOccurs="0">
			<xs:element name="array" type="callArrayType" />
			<xs:element name="struct" type="callStructType" />
		</xs:choice>
		<xs:attribute name="class" type="paramTypeAttrType" use="optional" />
	</xs:complexType>

	<xs:complexType name="respTypeType">
		<xs:choice minOccurs="0">
			<xs:element name="array" type="respArrayType" />
			<xs:element name="struct" type="respStructType" />
		</xs:choice>
		<xs:attribute name="class" type="paramTypeAttrType" use="optional" />
	</xs:complexType>

	<xs:complexType name="callStructType">
		<xs:sequence>
			<xs:element name="member" type="callMemberType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="respStructType">
		<xs:sequence>
			<xs:element name="member" type="respMemberType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="callArrayType">
		<xs:sequence>
			<xs:element name="type" type="callTypeType" />
		</xs:sequence>
		<xs:attribute name="apiArrayItemName" type="xs:string"
			use="optional" />
	</xs:complexType>

	<xs:complexType name="respArrayType">
		<xs:sequence>
			<xs:element name="type" type="respTypeType" />
		</xs:sequence>
		<xs:attribute name="apiArrayItemName" type="xs:string"
			use="optional" />
	</xs:complexType>

	<xs:simpleType name="paramTypeAttrType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\w+(\.\w+)*((\[\])|(\slist))?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="apiNameAttrType">
		<xs:restriction base="xs:string">
			<xs:pattern
				value="(\$(session_nick|session_uid|app_key))|([a-zA-Z0-9_\.]+)" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="memberTypeAttrType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="java.util.Date" />
			<xs:enumeration value="java.util.Date[]" />
			<xs:enumeration value="java.util.Date list" />

			<xs:enumeration value="string" />
			<xs:enumeration value="string[]" />
			<xs:enumeration value="java.lang.String" />
			<xs:enumeration value="java.lang.String[]" />
			<xs:enumeration value="string list" />
			<xs:enumeration value="java.lang.String list" />
			<xs:enumeration value="string set" />
			<xs:enumeration value="java.lang.String set" />

			<xs:enumeration value="int" />
			<xs:enumeration value="int[]" />
			<xs:enumeration value="java.lang.Integer" />
			<xs:enumeration value="java.lang.Integer[]" />
			<xs:enumeration value="int list" />
			<xs:enumeration value="java.lang.Integer list" />
			<xs:enumeration value="int set" />
			<xs:enumeration value="java.lang.Integer set" />

			<xs:enumeration value="long" />
			<xs:enumeration value="long[]" />
			<xs:enumeration value="java.lang.Long" />
			<xs:enumeration value="java.lang.Long[]" />
			<xs:enumeration value="long list" />
			<xs:enumeration value="java.lang.Long list" />
			<xs:enumeration value="long set" />
			<xs:enumeration value="java.lang.Long set" />

			<xs:enumeration value="boolean" />
			<xs:enumeration value="boolean[]" />
			<xs:enumeration value="java.lang.Boolean" />
			<xs:enumeration value="java.lang.Boolean[]" />
			<xs:enumeration value="boolean list" />
			<xs:enumeration value="java.lang.Boolean list" />
			<xs:enumeration value="boolean set" />
			<xs:enumeration value="java.lang.Boolean set" />

			<xs:enumeration value="byte" />
			<xs:enumeration value="byte[]" />
			<xs:enumeration value="java.lang.Byte" />
			<xs:enumeration value="java.lang.Byte[]" />
			<xs:enumeration value="byte list" />
			<xs:enumeration value="java.lang.Byte list" />
			<xs:enumeration value="byte set" />
			<xs:enumeration value="java.lang.Byte set" />

			<xs:enumeration value="short" />
			<xs:enumeration value="short[]" />
			<xs:enumeration value="java.lang.Short" />
			<xs:enumeration value="java.lang.Short[]" />
			<xs:enumeration value="short list" />
			<xs:enumeration value="java.lang.Short list" />
			<xs:enumeration value="short set" />
			<xs:enumeration value="java.lang.Short set" />

			<xs:enumeration value="char" />
			<xs:enumeration value="char[]" />
			<xs:enumeration value="java.lang.Character" />
			<xs:enumeration value="java.lang.Character[]" />
			<xs:enumeration value="char list" />
			<xs:enumeration value="java.lang.Character list" />
			<xs:enumeration value="char set" />
			<xs:enumeration value="java.lang.Character set" />

			<xs:enumeration value="float" />
			<xs:enumeration value="float[]" />
			<xs:enumeration value="java.lang.Float" />
			<xs:enumeration value="java.lang.Float[]" />
			<xs:enumeration value="float list" />
			<xs:enumeration value="java.lang.Float list" />
			<xs:enumeration value="float set" />
			<xs:enumeration value="java.lang.Float set" />

			<xs:enumeration value="double" />
			<xs:enumeration value="double[]" />
			<xs:enumeration value="java.lang.Double" />
			<xs:enumeration value="java.lang.Double[]" />
			<xs:enumeration value="double list" />
			<xs:enumeration value="java.lang.Double list" />
			<xs:enumeration value="double set" />
			<xs:enumeration value="java.lang.Double set" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="switchCaseTypeAttrType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string" />
			<xs:enumeration value="java.lang.String" />
			<xs:enumeration value="int" />
			<xs:enumeration value="java.lang.Integer" />
			<xs:enumeration value="long" />
			<xs:enumeration value="java.lang.Long" />
			<xs:enumeration value="boolean" />
			<xs:enumeration value="java.Lang.Boolean" />
			<xs:enumeration value="byte" />
			<xs:enumeration value="java.lang.Byte" />
			<xs:enumeration value="short" />
			<xs:enumeration value="java.lang.Short" />
			<xs:enumeration value="char" />
			<xs:enumeration value="java.lang.Character" />
			<xs:enumeration value="float" />
			<xs:enumeration value="java.lang.Float" />
			<xs:enumeration value="double" />
			<xs:enumeration value="java.lang.Double" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ssyangy/q/q-util/target/test-classes/q/serialize/mock/api-mapping-mc-array-pojo.xml
<?xml version="1.0" encoding="UTF-8"?>
<method xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd"
	interfaceName="q.serialize.album.AlbumService" interfaceVersion="1.0.0">

	<methodCall name="addAlbum" apiName="taobao.album.add">
		<params>
			<param>
				<type>
					<array>
						<type class="q.serialize.mock.domain.Pojo">
							<struct>
								<member name="title" apiName="name" type="string" />
								<member name="is3D" apiName="is_3D" type="boolean" />
								<member name="resultCount" apiName="result_count" type="int" />
							</struct>
						</type>
					</array>
				</type>
			</param>
		</params>
	</methodCall>

	<methodResponse>

	</methodResponse>
</method>

=== ssyangy/q/q-web/src/main/webapp/WEB-INF/json/category-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<param xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd">
	<type>
		<array>
			<type>
				<struct>
					<member name="id" apiName="id" apiType="string" />
					<member name="name" apiName="name" apiType="string" />
					<member name="avatarPath" apiName="avatarPath" apiType="string" />
					<member name="intro" apiName="intro" apiType="string" />
					<member name="groupNum" apiName="groupNum" apiType="int" />
					<member name="joinNum" apiName="joinNum" apiType="int" />
					<member name="time" apiName="screenTime" apiType="string" />
					<member name="createdTime" apiName="createdTime" apiType="string" />
				</struct>
			</type>
		</array>
	</type>
</param>

=== ssyangy/q/q-web/src/main/webapp/WEB-INF/json/weibo-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<param xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd">
	<type>
		<array>
			<type>
				<struct>
					<member name="id" apiName="id" apiType="string" />
					<member name="time" apiName="screenTime" apiType="string" />
					<member name="content" apiName="text" apiType="string" />
					<member name="picturePath" apiName="picturePath" apiType="string" />
					<member name="fav" apiName="favorited" apiType="boolean" />
					<member name="fromName" apiName="fromName" apiType="string" />
					<member name="fromUrl" apiName="fromUrl" apiType="string" />
					<member name="replyNum" apiName="replyNum" apiType="int" />
					<member name="retweetNum" apiName="retweetNum" apiType="int" />
					<member name="people" apiName="people">
						<type>
							<struct>
								<member name="id" apiName="id" apiType="string" />
								<member name="realName" apiName="screenName" apiType="string" />
								<member name="avatarPath" apiName="avatarPath" apiType="string" />
							</struct>
						</type>
					</member>
					<member name="quote" apiName="quote">
						<type>
							<struct>
								<member name="id" apiName="id" apiType="string" />
								<member name="time" apiName="screenTime" apiType="string" />
								<member name="content" apiName="text" apiType="string" />
								<member name="picturePath" apiName="picturePath" apiType="string" />
								<member name="fav" apiName="favorited" apiType="boolean" />
								<member name="fromName" apiName="fromName" apiType="string" />
								<member name="fromUrl" apiName="fromUrl" apiType="string" />
								<member name="replyNum" apiName="replyNum" apiType="int" />
								<member name="retweetNum" apiName="retweetNum" apiType="int" />
								<member name="people" apiName="people">
									<type>
										<struct>
											<member name="id" apiName="id" apiType="string" />
											<member name="realName" apiName="screenName" apiType="string" />
											<member name="avatarPath" apiName="avatarPath"
												apiType="string" />
										</struct>
									</type>
								</member>
							</struct>
						</type>
					</member>
				</struct>
			</type>
		</array>
	</type>
</param>

=== ssyangy/q/q-web/src/main/webapp/WEB-INF/json/group-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<param xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd">
	<type>
		<struct>
			<member name="hasPrev" apiName="hasPrev" apiType="boolean" />
			<member name="hasNext" apiName="hasNext" apiType="boolean" />
			<member name="groups" apiName="groups">
				<type>
					<array>
						<type>
							<struct>
								<member name="id" apiName="id" apiType="string" />
								<member name="name" apiName="name" apiType="string" />
								<member name="avatarPath" apiName="avatarPath" apiType="string" />
								<member name="intro" apiName="intro" apiType="string" />
								<member name="joinNum" apiName="joinNum" apiType="int" />
								<member name="latitude" apiName="latitude" apiType="double" />
								<member name="longitude" apiName="longitude" apiType="double" />
								<member name="time" apiName="screenTime" apiType="string" />
								<member name="createdTime" apiName="createdTime" apiType="string" />
								<member name="joined" apiName="joined" apiType="boolean">
									<switch>
										<case type="boolean" value="true" apiValue="true" />
									</switch>
								</member>
							</struct>
						</type>
					</array>
				</type>
			</member>
		</struct>
	</type>
</param>

=== ssyangy/q/q-util/src/test/resources/q/serialize/mock/object-mapping-switcher.xml
<?xml version="1.0" encoding="UTF-8"?>
<param xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd">
	<type>
		<struct>
			<member name="is3D" apiName="is_3D" apiType="boolean">
				<switch>
					<case type="boolean" value="true" apiValue="true" />
				</switch>
			</member>
			<member name="title" apiName="title" apiType="string" />
			<member name="z" apiName="z" apiType="int">
				<switch>
					<case type="boolean" value="true" apiValue="1" />
					<case type="boolean" value="false" apiValue="0" />
					<default apiValue="3" />
				</switch>
			</member>
		</struct>
	</type>
</param>

=== ssyangy/q/q-web/src/main/webapp/WEB-INF/json/people.xml
<?xml version="1.0" encoding="UTF-8"?>
<param xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd">
	<type>
		<struct>
			<member name="id" apiName="id" apiType="string" />
			<member name="realName" apiName="screenName" apiType="string" />
			<member name="avatarPath" apiName="avatarPath" apiType="string" />
			<member name="username" apiName="username" apiType="string" />
			<member name="followerNum" apiName="followerNum" apiType="int" />
			<member name="followingNum" apiName="followingNum" apiType="int" />
			<member name="weiboNum" apiName="weiboNum" apiType="int" />
			<member name="friendNum" apiName="friendNum" apiType="int" />
			<member name="email" apiName="email" apiType="string" />
			<member name="intro" apiName="intro" apiType="string" />
			<member name="time" apiName="screenTime" apiType="string" />
			<member name="createdTime" apiName="createdTime" apiType="string" />
			<member name="gender.value" apiName="gender" apiType="int" />
			<member name="following" apiName="following" apiType="boolean" />
			<member name="area" apiName="area">
				<type>
					<struct>
						<member name="id" apiName="id" apiType="string" />
						<member name="myProvince.name" apiName="province" apiType="string" />
						<member name="myCity.name" apiName="city" apiType="string" />
						<member name="myCounty.name" apiName="county" apiType="string" />
					</struct>
				</type>
			</member>
			<member name="hometown" apiName="hometown">
				<type>
					<struct>
						<member name="id" apiName="id" apiType="string" />
						<member name="myProvince.name" apiName="province" apiType="string" />
						<member name="myCity.name" apiName="city" apiType="string" />
						<member name="myCounty.name" apiName="county" apiType="string" />
					</struct>
				</type>
			</member>
		</struct>
	</type>
</param>

=== ssyangy/q/q-web/src/main/webapp/WEB-INF/json/message-replies.xml
<?xml version="1.0" encoding="UTF-8"?>
<param xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd">
	<type>
		<array>
			<type>
				<struct>
					<member name="id" apiName="id" apiType="string" />
					<member name="time" apiName="screenTime" apiType="string" />
					<member name="content" apiName="text" apiType="string" />
					<member name="sender" apiName="sender">
						<type>
							<struct>
								<member name="id" apiName="id" apiType="string" />
								<member name="realName" apiName="screenName" apiType="string" />
								<member name="avatarPath" apiName="avatarPath" apiType="string" />
							</struct>
						</type>
					</member>
				</struct>
			</type>
		</array>
	</type>
</param>

=== ssyangy/q/q-web/src/main/webapp/WEB-INF/json/message-replies-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<param xmlns="http://serialize.q.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://serialize.q.com.cn http://www.q.net/xsd/q-serialize.xsd">
	<type>
		<struct>
			<member name="hasPrev" apiName="hasPrev" apiType="boolean" />
			<member name="hasNext" apiName="hasNext" apiType="boolean" />
			<member name="replies" apiName="replies">
				<type>
					<array>
						<type>
							<struct>
								<member name="id" apiName="id" apiType="string" />
								<member name="time" apiName="screenTime" apiType="string" />
								<member name="createdTime" apiName="createdTime" apiType="string" />
								<member name="content" apiName="text" apiType="string" />
								<member name="sender" apiName="sender">
									<type>
										<struct>
											<member name="id" apiName="id" apiType="string" />
											<member name="realName" apiName="screenName" apiType="string" />
											<member name="avatarPath" apiName="avatarPath" apiType="string" />
										</struct>
									</type>
								</member>
							</struct>
						</type>
					</array>
				</type>
			</member>
		</struct>
	</type>
</param>
